version: "2"
linters:
  enable:
    - asasalint
    - durationcheck
    - errorlint
    - fatcontext
    - makezero
    - modernize
    - nilerr
    - nilnesserr
    - reassign
    - testifylint
    - unconvert
    - usestdlibvars
    - wastedassign
  exclusions:
    rules:
      - linters:
          - errcheck
        path: _test\.go
issues:
  max-issues-per-linter: 0
  max-same-issues: 0
formatters:
  enable:
    - gofumpt
    - goimports
